#!/bin/bash

name="$(echo ${0##*/} | sed 's/-/_/g')"
base="${0%/*}"; [ "$base" = "$0" ] && base="$PWD"

if [ ! -f "./config/user_config.py" ]; then
  echo === cp -av "$base/gcj/config" . >&2
  cp -av "$base/gcj/config" . || exit $?
  fi

if [ ! -f "./config/current_config.py" -a "$name" != gcj_init_contest ]; then
  echo Please run gcj-init-contest contest_id >&2
  exit 2
  fi

echo === python "$base/gcj/$name.py" --base_dir . "$@" >&2
python "$base/gcj/$name.py" --base_dir . "$@"
