#!/bin/sh

name="${0##*/}"; while [ "${name#*-}" != "$name" ]; do name="${name%%-*}_${name#*-}"; done
base="$(dirname "$0")" # "$(cd "$(dirname "$0")"; pwd -P)"


if [ ! -f "./config/user_config.py" ]; then
  echo === cp -av "$base/gcj/config" . >&2
  cp -av "$base/gcj/config" . || exit $?
  fi

if [ ! -f "./config/current_config.py" -a "$name" != gcj_init_contest ]; then
  echo Please run gcj-init-contest before $name. >&2
  exit 2
  fi

echo === python "$base/gcj/$name.py" --base_dir . "$@" >&2
python "$base/gcj/$name.py" --base_dir . "$@"
